services:
  - type: web
    name: fb-token-tool
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: FB_APP_ID
        sync: false
      - key: FB_APP_SECRET
        sync: false
